# Generated by Django 4.0.1 on 2022-05-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_recepient_message_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
